apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuxt-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nuxt
  template:
    metadata:
      labels:
        app: nuxt
    spec:
      containers:
      - name: nuxt
        image: front:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000